export enum QueryFunction {
    SYMBOL_SEARCH = "SYMBOL_SEARCH",
    SYMBOL_TIME_SERIES_DAILY_ADJUSTED = "TIME_SERIES_DAILY_ADJUSTED",
    COMPANY_OVERVIEW = "OVERVIEW",
    MARKET_STATUS = "MARKET_STATUS",
  }